-- MySQL Script generated by MySQL Workbench
-- Tue May 21 03:57:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cinema_complex` DEFAULT CHARACTER SET utf8 ;
USE `db_cinema_complex` ;

-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_cycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_cycle` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `weekday` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_cycle`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (0, 'Wed', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (1, 'Thu', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (2, 'Fri', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (3, 'Sat', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (4, 'Sun', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (5, 'Mon', DEFAULT);
INSERT INTO `db_cinema_complex`.`tbl_cycle` (`id`, `weekday`, `date`) VALUES (6, 'Tue', DEFAULT);

COMMIT;

