-- MySQL Script generated by MySQL Workbench
-- Wed May 15 18:48:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cinema_complex` DEFAULT CHARACTER SET utf8 ;
USE `db_cinema_complex` ;

-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_roles` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_users` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(500) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `salt` VARCHAR(32) NOT NULL,
  `role_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_users_tbl_roles1_idx` (`role_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_tbl_users_tbl_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_cinema_complex`.`tbl_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_permissions` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `access` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_user_details` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `surname` VARCHAR(500) NOT NULL,
  INDEX `fk_tbl_user_details_tbl_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_tbl_user_details_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_cinema_complex`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_login_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_login_sessions` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `expiration` INT(11) NOT NULL,
  `sess_identifier` VARCHAR(100) NOT NULL,
  INDEX `fk_tbl_login_sessions_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_login_sessions_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_cinema_complex`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_login_attempts` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `attempts` TINYINT(1) NOT NULL,
  `ip_address` VARCHAR(50) NOT NULL,
  `lock` INT(11) NULL,
  `user_id` MEDIUMINT(8) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_login_attempts_tbl_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_tbl_login_attempts_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_cinema_complex`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_rating` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_genre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_movies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `release_date` DATETIME NOT NULL,
  `runtime` INT(10) NOT NULL,
  `rating_id` INT UNSIGNED NOT NULL,
  `slug` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_movie_tbl_rating1_idx` (`rating_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_tbl_movie_tbl_rating1`
    FOREIGN KEY (`rating_id`)
    REFERENCES `db_cinema_complex`.`tbl_rating` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_no` VARCHAR(45) NOT NULL,
  `columns` INT(5) NOT NULL,
  `rows` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_showing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_showing` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `movie_id` INT UNSIGNED NOT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_showing_tbl_movie1_idx` (`movie_id` ASC),
  INDEX `fk_tbl_showing_tbl_room1_idx` (`room_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_tbl_showing_tbl_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_cinema_complex`.`tbl_movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_showing_tbl_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `db_cinema_complex`.`tbl_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_ticket` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `movie_id` INT UNSIGNED NOT NULL,
  `seat` INT UNSIGNED NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_tbl_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_ticket_tbl_movie1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_table1_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_cinema_complex`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ticket_tbl_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_cinema_complex`.`tbl_movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_movie_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_movie_genre` (
  `movie_id` INT UNSIGNED NOT NULL,
  `genre_id` INT UNSIGNED NOT NULL,
  INDEX `fk_table1_tbl_movie1_idx` (`movie_id` ASC),
  INDEX `fk_table1_tbl_genre1_idx` (`genre_id` ASC),
  CONSTRAINT `fk_table1_tbl_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_cinema_complex`.`tbl_movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tbl_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `db_cinema_complex`.`tbl_genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_roles` (`id`, `name`) VALUES (1, 'Administrator');
INSERT INTO `db_cinema_complex`.`tbl_roles` (`id`, `name`) VALUES (2, 'User');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_permissions` (`id`, `name`, `access`) VALUES (0, 'BACKEND_ACCESS', 3);
INSERT INTO `db_cinema_complex`.`tbl_permissions` (`id`, `name`, `access`) VALUES (1, 'ADD_USERS', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_rating`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_rating` (`id`, `name`) VALUES (0, 'G');
INSERT INTO `db_cinema_complex`.`tbl_rating` (`id`, `name`) VALUES (1, 'PG');
INSERT INTO `db_cinema_complex`.`tbl_rating` (`id`, `name`) VALUES (2, 'PG-13');
INSERT INTO `db_cinema_complex`.`tbl_rating` (`id`, `name`) VALUES (3, 'R');
INSERT INTO `db_cinema_complex`.`tbl_rating` (`id`, `name`) VALUES (4, 'NC-17');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_genre`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (0, 'Action');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (1, 'Adventure');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (2, 'Comedy');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (3, 'Crime Film');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (4, 'Drama');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (5, 'Horror');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (6, 'Musical');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (7, 'Romance');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (8, 'Romantic Comedy');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (9, 'Science Fiction');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (10, 'Thriller');
INSERT INTO `db_cinema_complex`.`tbl_genre` (`id`, `name`) VALUES (11, 'Western');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_cinema_complex`.`tbl_room`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_cinema_complex`;
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (0, 'Cinema 1', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (1, 'Cinema 2', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (2, 'Cinema 3', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (3, 'Cinema 4', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (4, 'Cinema 5', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (5, 'Cinema 6', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (6, 'Cinema 7', 5, 5);
INSERT INTO `db_cinema_complex`.`tbl_room` (`id`, `room_no`, `columns`, `rows`) VALUES (7, 'Cinema 8', 5, 5);

COMMIT;

