-- MySQL Script generated by MySQL Workbench
-- Fri May 24 00:14:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cinema_complex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cinema_complex` DEFAULT CHARACTER SET utf8 ;
USE `db_cinema_complex` ;

-- -----------------------------------------------------
-- Table `db_cinema_complex`.`tbl_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cinema_complex`.`tbl_ticket` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `showing_id` INT UNSIGNED NOT NULL,
  `time` VARCHAR(5) NOT NULL,
  `seat` INT UNSIGNED NOT NULL,
  INDEX `fk_table1_tbl_users1_idx` (`user_id` ASC),
  INDEX `fk_tbl_ticket_tbl_showing1_idx` (`showing_id` ASC),
  CONSTRAINT `fk_table1_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_cinema_complex`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ticket_tbl_showing1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `db_cinema_complex`.`tbl_showing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
